### ISSUE TITLE
Google Maps embeds showing error

### ISSUE THREAD

**Issue by ChaosExAnima** [nysenate/NYSenate.gov#13]
Howdy!

With a recent change to the Google Maps embeds, the nysenate.gov site is showing errors in it's embeds:
https://www.nysenate.gov/district/18

![screenshot from 2018-08-21 15-27-20](https://user-images.githubusercontent.com/1760168/44424308-b8bd8a00-a556-11e8-85dc-cf2747952033.png)

This error is due to a change in how Google has handled it's API keys for Maps: https://developers.google.com/maps/billing/important-updates

It can be resolved by creating a billing account for the API key assigned to the site.

Hope this helps! :)

**Comment by rtblair** [comment]
Thank you @ChaosExAnima! We are aware of this issue and working to deploy a fix as soon as possible. I'll leave the ticket open until the issue is resolved.

**Comment by ChaosExAnima** [comment]
You're very welcome.

**Comment by rtblair** [comment]
Resolved.
