### ISSUE TITLE
VAT main page doesn't list Articles

### ISSUE THREAD

**Issue by michaelkolber** [nysenate/NYSenate.gov#15]
When visiting https://www.nysenate.gov/legislation/laws/VAT, it shows the general legislation page (the same one as https://www.nysenate.gov/legislation/). This is contrast to, for example, https://www.nysenate.gov/legislation/laws/ABP, which lists the Articles. The VAT page should also list the articles.

**Comment by routinet** [comment]
This issue was due to statute import's intermittent failures.  This has since been addressed with nys_openleg live API calls.

Repo updated in bulk. Closing outdated issues.
