### ISSUE TITLE
Text versions of Senate Bills do not provide full text without interacting with page (View More/View Less) or by downloading a PDF (unacceptable as text version)

### ISSUE THREAD

**Issue by larrytimmins** [nysenate/NYSenate.gov#16]
As example, recently approved bill, S5575B, by Sen Kevin Thomas, states it has the full txt of the bill.   However the site doesn't not have the raw text of the bill -- only an interactive page which by default shows partial text (you must interact and click View More).

The alternative offered is not acceptiable as it is not text, but a proprietary Adobe PDF format.    While PDF is excellent for email and print format; ML analysis for privacy compliance reviews and multi-linqual translations and search assistance should be able to reference a separate file that is actually clean text as a feature without PHP or other web framework constructs (View More/View Less) interspersed within the full text body.

Webpage in question (as example): https://www.nysenate.gov/legislation/bills/2019/S5575

I am gladly available for comment, encouragement and hopefully NYS taxpayers can expect to have a format consumable by all state taxpayers in the future.

**Comment by routinet** [comment]
Thanks for taking the time to create this issue.  

The NYSenate.gov public website is a platform primarily geared towards facilitating engagement between constituents and NY State Senators and their staff.  Almost all of the related data, such as pending or resolved legislation, statutes, transcripts, etc., is sourced from another application created by NYSS - OpenLegislation.  

You can access OpenLegislation at https://legislation.nysenate.gov/.  OL also has an API accessible to the public.  The public website actually uses that same API to fetch the text of legislation, and even sources the downloadable PDF there.  You can find more information on how to get started with the API at https://legislation.nysenate.gov/static/docs/html/index.html.  From there, you can query the plain-text version of any bill, as well as any other meta-data that may be of interest.

**Comment by larrytimmins** [comment]
Hi Steve,
Thank you very much for such a quick, helpful and thorough response.  Great
answer. I will make my way over there to check the text versiin available.
Part of the effort is rhe help provide guidance and consolidate research
for the general SME's in New York of any ethnicity.

All the best. Stay safe. Be well.
Larry

**Comment by routinet** [comment]
Repo updated in bulk. Closing outdated issues.
