### ISSUE TITLE
Apostrophes being encoded wrong

### ISSUE THREAD

**Issue by brireley** [nysenate/NYSenate.gov#2]
In the 'contact your senator' page to compose your message, the grayed out field displaying the senator's name is displaying apostrophes as &#039 -- see Peter F. O'Mara for an example. Cheers!

**Comment by rtblair** [comment]
Thank you for this report. We'll add it to our internal queue.

**Comment by rtblair** [comment]
@brireley, can you provide details about the browser you are using. Also, can you provide a link to the URL where you are encountering this error?

**Comment by routinet** [comment]
Repo updated in bulk.  Closing outdated issues.
