### ISSUE TITLE
If already voted Bills page should higilht your aye/nea choice

### ISSUE THREAD

**Issue by Typhoon87** [nysenate/NYSenate.gov#26]
Currently after clicking yea/nea going off the page for a bill and then going back it allows you to click yea/nea again.

Perhaps this system should note when you have already made a decision on a specific bill.. One option could be the box could say you have previously said you supported/not support this bill.

**Comment by routinet** [comment]
Our site does track a user's vote.  After voting, you can do to your dashboard and view your submitted votes on the "Bills" tab.  The ability to submit multiple votes is purposeful - people can always change their mind.  In the background, however, the vote is not counted multiple times.  Any time a user submits a vote, any previous entry for that bill is replaced.
Having some kind of indication on the voting widget that a vote is already registered is a good idea, though.  I will add that to our list of improvements.

**Comment by Typhoon87** [comment]
Thank you for getting back on this.
A visible UI note that you have already voted on something allows you to ensure if a user changes their mind you can prompt them to put why in a free form text field as well.

**Comment by routinet** [comment]
We currently allow for a constituent to send a message to their senator when submitting a bill vote.  However, we limit that ability to only the first vote to prevent spam/DDOS attacks.  While the use-case of "I changed my mind" is valid, there is simply no way to detect that intention from the form submission.
